### ISSUE TITLE
Possibility to override all image corner radii

### ISSUE THREAD

**Issue by LauBCra** [parley-messaging/android-library#47]
Currently for the agent and user image corner radius, only a single radius can be set for all corners. However our drawables don't have the same radius for each corner. The result doesn't look very nice. Best seen with the placeholder, as in the included image.

Could it be made possible to override all corner radii?

![chat - image radius](https://github.com/parley-messaging/android-library/assets/156925765/0b570787-b693-40ec-8ad7-b593e2b29963)

**Comment by LauBCra** [comment]
This is no longer an issue after fixing issue 45 in 3.9.4

**Comment by alexkok** [comment]
Ah true, that was caused by the same bug, thanks!
