### ISSUE TITLE
Chat keeps scrolling to bottom

### ISSUE THREAD

**Issue by mennovogel** [parley-messaging/android-library#53]
The chat keeps scrolling to the bottom if the last or second-last chat message is visible. This is partly due to our implementation, because we use a polling mechanism to update the chat, instead of push. But I don't see a reason why this works like this.
There is already a check in place to see if new messages have been downloaded, if the messages are the same the view should not scroll.

https://github.com/parley-messaging/android-library/assets/2795333/a940bb56-0c63-4371-b116-d64c2291e60b

This behaviour is caused by the `ParleyView` that listens for `onReceivedMoreMessages(..)`, this function calls `renderMessages()`, this triggers a scroll if you are already close to the bottom (last or second-last message is visible).

I think that `onReceivedMoreMessages(..)` should only be called if the received messages are not the same.

**Comment by alexkok** [comment]
Thanks for reporting. Since this is intended to trigger only on reconnecting, it was never an issue earlier.

But the listener could be prevented to happen when no change is done yes 👍

**Comment by mennovogel** [comment]
Thanks for merging this, could you also create a new version with this fix please?

**Comment by alexkok** [comment]
Sure! Will do that tomorrow morning 👍

**Comment by alexkok** [comment]
Fixed in [3.9.5](https://github.com/parley-messaging/android-library/releases/tag/3.9.5) 🚀
