### ISSUE TITLE
Update TrustKit to 1.1.5

### ISSUE THREAD

**Issue by mennovogel** [parley-messaging/android-library#63]
We would like to have the latest version of TrustKit, version 1.1.5 (this version is not officially tagged, but it is released). 

For some reason our project crashes with a NullPointerException in `Parley.configure(...)` when we compile the project with TrustKit 1.1.2.

**Comment by alexkok** [comment]
Maybe related to https://github.com/datatheorem/TrustKit-Android/issues/85#issuecomment-812802403?

We'll bump it and release a new version 👍

**Comment by alexkok** [comment]
Released in [3.9.7](https://github.com/parley-messaging/android-library/releases/tag/3.9.7) 🚀
